spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
server.port=${PORT:8080}
spring.thymeleaf.cache=true
fish.audio.api.key=${FISH_AUDIO_API_KEY}
fish.audio.model.id=db857de9b1be4f9cb53799daaa69218e
server.tomcat.max-threads=10
server.tomcat.min-spare-threads=2
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1